theme = "simple-blog"
baseURL = "dw3624 Data Science Blog"
title = "https://tejava.netlify.app/"
copyright = "© 2020 copyright text."
paginate = 3
languageCode = "ko-kr"
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
     name = "GitHub"
    url = "https://github.com/dw3624/My-Blog"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"